### ISSUE TITLE
Pedigree: Generate PED for all `Genom` sample entries

### ISSUE THREAD

**Issue by xiamaz** [LaborBerlin/hum-dragen-routine#25]

**Comment by xiamaz** [comment]
solved with `pelextract/generate_peds.sh` this outputs pedigrees for all batches into a defined directory for now.

**Comment by your-highness** [comment]
Unfortunately, this does not work as intended with conda environment `hum-dragen-routine`. Message:
```bash
>bash generate_peds.sh
2020-05-19-AHL3TTDRXX.csv failed with error: Failed to parse sample entry: "13-1257tn-Exome"
2020-06-10-AHLCK5DRXX.csv failed with error: Failed to parse sample entry: "LB20-945b-CTv2"
2020-06-18-AHLF77DRXX.csv failed with error: Failed to parse sample entry: "14-1114tn-Exome"
2020-08-21-BHN7LMDRXX.csv failed with error: Failed to parse sample entry: "13-0283c-SW"
2020-08-28-BHN7LCDRXX.csv failed with error: Failed to parse sample entry: "15-2851b-BCv2"
2020-09-11-AHNKF5DRXX.csv failed with error: Failed to parse sample entry: "15-2369b-BCv2"
2020-09-18-BHNKG7DRXX.csv failed with error: Failed to parse sample entry: "12-0386b-BCv2"
2020-10-08-AHTTJMDRXX.csv failed with error: Failed to parse sample entry: "12-1736b-BCv2"
2020-10-30-BHV5YYDRXX.csv failed with error: Failed to parse sample entry: "12-1237b-Exome"
2020-11-12-AHVCYLDRXX.csv failed with error: Failed to parse sample entry: "Alex-chr12-HBBv2"
2020-11-20-BHVWTGDRXX.csv failed with error: Failed to parse sample entry: "15-0690-BCv2"
2020-12-28-BHYLJ3DRXX.csv failed with error: Failed to parse sample entry: "14-1720b-BCv2"
2021-01-29-AH2K3MDRXY.csv failed with error: Failed to parse sample entry: "13-0426b-BCv3"
2021-02-12-AH2JL2DRXY.csv failed with error: Failed to parse sample entry: "11-1709-BCv3"
2021-02-18-BH2KKGDRXY.csv failed with error: Failed to parse sample entry: "14-0800b-BCv3"
2021-03-05-BH325WDRXY.csv failed with error: Failed to parse sample entry: "RV-17016192m-Exome"
2021-03-12-AH2YGGDRXY.csv failed with error: Failed to parse sample entry: "RV-20116248-sDAGv2"
2021-03-19-BH2YHTDRXY.csv failed with error: Failed to parse sample entry: "RV-20118760-BCv3"
2021-03-26-AH5FC2DRXY.csv failed with error: Failed to parse sample entry: "RV-20118760wdh-BCv3"
2021-03-31-AH5FGVDRXY.csv failed with error: Failed to parse sample entry: "14-0675-BCv3"
2021-05-28.csv failed with error: Failed to extract date and samplesheet ID from: "2021-05-28.csv"
2021-10-01-BH3LVLDMXY.csv failed with error: Failed to parse sample entry: "NA-12878WGS-Genom"
2021-10-14-BHKM3LDRXY.csv failed with error: Failed to parse sample entry: "NA-12878m-Exomev8"
2021-11-11-BHM3FFDRXY.csv failed with error: Failed to parse sample entry: "NA12878eXTHS2-Exomev8"
2021-11-25-BH3MLNDMXY.csv failed with error: Failed to parse sample entry: "NA-12878me2-Exomev8"
2022-03-18-AH7JGVDMXY.csv failed with error: Failed to parse sample entry: "NA-12878WGS-Genom-size"
2022-04-13-BH7MHCDMXY.csv failed with error: Failed to parse sample entry: "NA-12878WGS-GenomDoubleSize"
2022-07-15-AHF2LJDMXY.csv failed with error: Failed to parse sample entry: "NA24143WGSneu-GenomDoubleSize"
Failed to parse 14-1107, line ignored
Failed to parse 17-3210, line ignored
Failed to parse 13-1661, line ignored
Failed to parse 16-2153, line ignored
Traceback (most recent call last):
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/./batcher.py", line 183, in <module>
    parse_samplesheets(args.output, args.samplesheets, args.db, args.pel)
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/./batcher.py", line 163, in parse_samplesheets
    batchdate = min([s.date for s in overlapping_samples]).isoformat()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() arg is an empty sequence
generate_peds.sh: line 17: output/lbids/*.lst: No such file or directory
usage: Scrape PEL sheet [-h] [--pel_sheet PEL_SHEET] [--ids IDS [IDS ...]] output
Scrape PEL sheet: error: argument --ids: expected at least one argument
```

**Comment by your-highness** [comment]
Also `./extract.py` fails when the list of given `lbids` does not contain the "index_id", e.g.:
```python
>python ./extract.py --ids LB22-1174 --pel_sheet "$PEL_PATH" pedigrees
Failed to parse 14-1107, line ignored
Failed to parse 17-3210, line ignored
Failed to parse 13-1661, line ignored
Failed to parse 16-2153, line ignored
Traceback (most recent call last):
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 182, in <module>
    process_ped(args.pel_sheet, args.ids, args.output)
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 108, in process_ped
    valid, comment = rule(filtered, ids)
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 84, in rule_index_younger_than_parents
    index_entry = [f for f in filtered if f['lb_id'] == index_id][0]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
or
```python
>python ./extract.py --ids LB22-1174 LB22-1173 --pel_sheet "$PEL_PATH" pedigrees
Failed to parse 14-1107, line ignored
Failed to parse 17-3210, line ignored
Failed to parse 13-1661, line ignored
Failed to parse 16-2153, line ignored
Traceback (most recent call last):
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 182, in <module>
    process_ped(args.pel_sheet, args.ids, args.output)
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 108, in process_ped
    valid, comment = rule(filtered, ids)
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 84, in rule_index_younger_than_parents
    index_entry = [f for f in filtered if f['lb_id'] == index_id][0]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

When adding `index_id` it works as intended:
```python
>python ./extract.py --ids LB22-1174 LB22-3032 --pel_sheet "$PEL_PATH" pedigrees
Failed to parse 14-1107, line ignored
Failed to parse 17-3210, line ignored
Failed to parse 13-1661, line ignored
Failed to parse 16-2153, line ignored
Added 0 non family entries
Writing PED file for LB22_3032_FAM
```

I assume the following section has to be adapted to check not only in `filtered` but for existence in `infos` defined in `process_ped`:
https://github.com/LaborBerlin/hum-dragen-routine/blob/8f33be110017677aac270c4b4a1a1f30eee1ec8a/pelextract/extract.py#L83-L84

**Comment by xiamaz** [comment]
After major refactor on the https://github.com/xiamaz/pel-transfer-tn project, that project has been extended to support a much higher degree of configurability.

It should make sense to move the PED generation logic into that project and either execute or pull PED files from a folder containing all pedigree files for genomes.

**Comment by xiamaz** [comment]
Solved in https://github.com/xiamaz/pel-transfer-tn
