### ISSUE TITLE
Pedigree. Make `pelextract/extract.py` work with all entries instead of `filtered` only

### ISSUE THREAD

**Issue by your-highness** [LaborBerlin/hum-dragen-routine#42]
**Background:**
Also `./extract.py` fails when the list of given `lbids` does not contain the "index_id", e.g.:
```python
>python ./extract.py --ids LB22-1174 --pel_sheet "$PEL_PATH" pedigrees
Failed to parse 14-1107, line ignored
Failed to parse 17-3210, line ignored
Failed to parse 13-1661, line ignored
Failed to parse 16-2153, line ignored
Traceback (most recent call last):
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 182, in <module>
    process_ped(args.pel_sheet, args.ids, args.output)
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 108, in process_ped
    valid, comment = rule(filtered, ids)
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 84, in rule_index_younger_than_parents
    index_entry = [f for f in filtered if f['lb_id'] == index_id][0]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
or
```python
>python ./extract.py --ids LB22-1174 LB22-1173 --pel_sheet "$PEL_PATH" pedigrees
Failed to parse 14-1107, line ignored
Failed to parse 17-3210, line ignored
Failed to parse 13-1661, line ignored
Failed to parse 16-2153, line ignored
Traceback (most recent call last):
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 182, in <module>
    process_ped(args.pel_sheet, args.ids, args.output)
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 108, in process_ped
    valid, comment = rule(filtered, ids)
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/helmuth/workspace/hum-dragen-routine.git/pelextract/extract.py", line 84, in rule_index_younger_than_parents
    index_entry = [f for f in filtered if f['lb_id'] == index_id][0]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

When adding `index_id` it works as intended:
```python
>python ./extract.py --ids LB22-1174 LB22-3032 --pel_sheet "$PEL_PATH" pedigrees
Failed to parse 14-1107, line ignored
Failed to parse 17-3210, line ignored
Failed to parse 13-1661, line ignored
Failed to parse 16-2153, line ignored
Added 0 non family entries
Writing PED file for LB22_3032_FAM
```

I assume the following section has to be adapted to check not only in `filtered` but for existence in `infos` defined in `process_ped`:
https://github.com/LaborBerlin/hum-dragen-routine/blob/8f33be110017677aac270c4b4a1a1f30eee1ec8a/pelextract/extract.py#L83-L84

**References:**
#25

**Comment by xiamaz** [comment]
Yes, this is currently working as intended, as all LB-IDs that should be exported should be known explicitly. If the index is not in our currently exported batch, the script might be using the wrong PEL entry. (As some samples are sequenced for multiple indexes)

**Comment by your-highness** [comment]
Ok. Sounds reasonable but does not capture all possible cases, _e.g._ resquencing.

We should also make sure that PED is generated correctly when only 2 samples of a trio are in a batch. Currently, a duo PED is generated in this case.

**Comment by xiamaz** [comment]
Solved in https://github.com/xiamaz/pel-transfer-tn
